// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCNV8Crefs5ah9aZF8nXe9c_oOU7_zPwU',
    appId: '1:956076657726:web:a0a3ec42ac9bfcffdd156f',
    messagingSenderId: '956076657726',
    projectId: 'aquasensetest-62959',
    authDomain: 'aquasensetest-62959.firebaseapp.com',
    databaseURL: 'https://aquasensetest-62959-default-rtdb.firebaseio.com',
    storageBucket: 'aquasensetest-62959.appspot.com',
    measurementId: 'G-TTCYFHCHGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0AlgluHt2Y_hOtauD8oMf82dPodKWfiE',
    appId: '1:956076657726:android:43f18a1bef1b122cdd156f',
    messagingSenderId: '956076657726',
    projectId: 'aquasensetest-62959',
    databaseURL: 'https://aquasensetest-62959-default-rtdb.firebaseio.com',
    storageBucket: 'aquasensetest-62959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4s5shsPpkMorx34qO9vAWxHB1g-XWPfg',
    appId: '1:956076657726:ios:fea24d9fd697aa69dd156f',
    messagingSenderId: '956076657726',
    projectId: 'aquasensetest-62959',
    databaseURL: 'https://aquasensetest-62959-default-rtdb.firebaseio.com',
    storageBucket: 'aquasensetest-62959.appspot.com',
    iosClientId: '956076657726-mukeig0l14lpf3cmsqq3b0kostfg8poq.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4s5shsPpkMorx34qO9vAWxHB1g-XWPfg',
    appId: '1:956076657726:ios:40633d0712823062dd156f',
    messagingSenderId: '956076657726',
    projectId: 'aquasensetest-62959',
    databaseURL: 'https://aquasensetest-62959-default-rtdb.firebaseio.com',
    storageBucket: 'aquasensetest-62959.appspot.com',
    iosClientId: '956076657726-6lfoip5qo37hag7ggfklbt2gdl9rtfvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasenseapp.RunnerTests',
  );
}
