// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtIluNNVJDCv0pA-ruHaNnN2ZexIpo4x4',
    appId: '1:701067318804:web:adbeabf6b3ce034ced7901',
    messagingSenderId: '701067318804',
    projectId: 'aquasense-v1',
    authDomain: 'aquasense-v1.firebaseapp.com',
    databaseURL: 'https://aquasense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-v1.appspot.com',
    measurementId: 'G-VYJBZDVRFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb7rLYlbiO4clhUfeeMYJCkREleSA1_KE',
    appId: '1:701067318804:android:ba6332826bd5dd59ed7901',
    messagingSenderId: '701067318804',
    projectId: 'aquasense-v1',
    databaseURL: 'https://aquasense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOCQ0yD8qgn4HA2Gv5suzaspaGYy2Q07c',
    appId: '1:701067318804:ios:e1f08a1b31c0d093ed7901',
    messagingSenderId: '701067318804',
    projectId: 'aquasense-v1',
    databaseURL: 'https://aquasense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-v1.appspot.com',
    iosClientId: '701067318804-dv7qjgiev4qnpen147ifjj869r2irbkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOCQ0yD8qgn4HA2Gv5suzaspaGYy2Q07c',
    appId: '1:701067318804:ios:9d128872316aa940ed7901',
    messagingSenderId: '701067318804',
    projectId: 'aquasense-v1',
    databaseURL: 'https://aquasense-v1-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-v1.appspot.com',
    iosClientId: '701067318804-daqh6bgs8hhngqcut93fearseg1ctp5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasenseapp.RunnerTests',
  );
}
